# Generated by Django 2.2.2 on 2019-06-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobreNome', models.CharField(max_length=50)),
                ('fomacao', models.CharField(max_length=100)),
                ('idade', models.IntegerField(max_length=5)),
                ('telefone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
