# Generated by Django 2.2.2 on 2019-06-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudante', '0002_auto_20190613_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobreNome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
